### ISSUE TITLE
Need to support Identity licence on CRUD operation on Salesforce data

### ISSUE THREAD

**Issue by gabpaquin** [Prepsmith/eic-auth#1]
@flyerhzm  we have now two types for licences on Salesforce: 

![screen shot 2016-11-06 at 7 17 17 pm](https://cloud.githubusercontent.com/assets/705585/20037209/606f873e-a456-11e6-968f-adb5d42e50a1.png)

If a user has a Identify licence, we should use the the prepsmith bot user to authenticate against salesforce to perform CRUD operation.

If the user has a salesforce licence, he should be using his own credentials to perform CRUD operation on salesforce data

**Comment by flyerhzm** [comment]
@gabpaquin it's done on staging, need to deploy iam-api and crm-api, the logic is if license is Salesforce, use user client, otherwise, use bot client.

**Comment by gabpaquin** [comment]
@flyerhzm thanks!
